### ISSUE TITLE
insert host data into table

### ISSUE THREAD

**Issue by chipfy** [productsupcom/ansible-dyninv-mysql#1]
Table: host,group,childgroups,hostgroups
How  I insert my host list  data into the tables?

**Comment by chipfy** [comment]
have sample?

**Comment by terwey** [comment]
The best approach is to use a MySQL editor, maybe one of the following:
- [Sequel Pro for Mac](http://www.sequelpro.com/)
- [HeidiSQL for Windows](http://www.heidisql.com/)
- [MySQL Workbench Crossplatform](https://www.mysql.de/products/workbench/)

However if you want to do it manually here are some example insert queries:

For the host:

```
INSERT INTO `host` (`host`, `hostname`, `variables`, `enabled`)
VALUES
    ('something.dns.com', 'something','{}', 1);
```

For the group:

```
INSERT INTO `group` (`name`, `variables`, `enabled`)
VALUES
    ('common', '{}', 1);
```

And then for the hostgroup:

```
INSERT INTO `hostgroups` (`host_id`, `group_id`)
VALUES
    (1, 1); -- assuming both are id 1
```

**Comment by terwey** [comment]
Please let us know if you are having further issues or questions.
