### ISSUE TITLE
The host must be in a group?  If host is NOT in a group,  --list does not show it.

### ISSUE THREAD

**Issue by askdaddy** [productsupcom/ansible-dyninv-mysql#3]
In yaml inventroy, we can define a absolute host
```
mail.example.com

[webservers]
foo.example.com
bar.example.com

[dbservers]
one.example.com
two.example.com
three.example.com
```

like mail.example.com above.

but in Dynamic Inventory, the host must be in a group?

**Comment by askdaddy** [comment]
update:
The ansible doc said:
```
## Default groups
There are two default groups: all and ungrouped. all contains every host. ungrouped contains all hosts that don’t have another group aside from all. Every host will always belong to at least 2 groups. Though all and ungrouped are always present, they can be implicit and not appear in group listings like group_names.
```

So~~~, if the host does not belog any group,we need to add it into  `ungrouped` when --list called! Is that right?

**Comment by terwey** [comment]
Hi @askdaddy,

The implementation of this Dynamic Inventory indeed demands a _group_ to be set.

This isn't the case for the `yaml` format, but those are also meant for quick setup and throwaway. The only workaround I can offer is to simply have a _group_ that you assign everything to if you're not splitting up _hosts_ by category.

This was a design choice for this specific Dynamic Inventory and thus not a bug/issue.

**Comment by askdaddy** [comment]
```
CREATE VIEW `inventory`
AS (SELECT
   `group`.`name` AS `group`,
   `host`.`host` AS `host`,
   `host`.`hostname` AS `hostname`,
   `host`.`variables` AS `host_vars`
FROM (`group` left join (`host` left join `hostgroups` ON ((`host`.`id` = `hostgroups`.`host_id`))) ON ((`hostgroups`.`group_id` = `group`.`id`)))
WHERE `host`.`enabled` = 1 AND `group`.`enabled` = 1)
UNION
(SELECT
'ungrouped' AS `group`,
`host`.`host` AS `host`,
`host`.`hostname` AS `hostname`,
`host`.`variables` AS `host_vars`
FROM `host` LEFT JOIN `hostgroups` ON  `host`.`id` = `hostgroups`.`host_id`
WHERE `hostgroups`.`group_id` IS NULL);
```

I ve changed my view above.  
then `ansible -i inventory.py all --list-hosts` will show all hosts even not in a group
run `ansible -i inventory.py ungrouped --list-hosts` will show hosts that not in any group.
@terwey
