### ISSUE TITLE
Got a python exception when var is null.

### ISSUE THREAD

**Issue by beckxie** [productsupcom/ansible-dyninv-mysql#7]
# Issue Description

Hi,

I got a exception on `line:189` when `'vars' not in self.inventory[groupname]`.
https://github.com/productsupcom/ansible-dyninv-mysql/blob/80425587e947c812b2cbc3913cda8c76c28c2916/mysql.py#L189

> Fixes a bug where a group might not have variables(8b7192963bc014ef5c52b0244c470b21065d39d1)

Maybe `self.inventory[group]` should be `dict`, not `list`.
Is that right?  @terwey @tanji 

https://github.com/productsupcom/ansible-dyninv-mysql/blob/80425587e947c812b2cbc3913cda8c76c28c2916/mysql.py#L135-L136

# Environment
1. Python 2.7.5

# Steps to reproduce
1. git clone https://github.com/productsupcom/ansible-dyninv-mysql.git
2. Prepare the table schema: `tables.sql`
3. Insert data to MySQL: 
```sql
insert into `host` (id,host,hostname,variables,enabled) values (1,'10.128.0.1','node1','',1);
insert into `group` (id,name,variables,enabled) values (1,'group_A','',1);
insert into `hostgroups` (host_id,group_id) values (1,1);
```

4. Execute command:
```bash
python mysql.py --list
```

5. Expected result:
```bash
$ python mysql.py --list
Traceback (most recent call last):
  File "mysql.py", line 254, in <module>
    MySQLInventory()
  File "mysql.py", line 57, in __init__
    self.update_cache()
  File "mysql.py", line 189, in update_cache
    if not self.inventory[group]['hosts']:
TypeError: list indices must be integers, not str
```

**Comment by tanji** [comment]
In which context do you get this exception? We've never encountered it.

**Comment by tanji** [comment]
Thanks for adding reproducible code, I understand where this comes from.
Generally speaking `group` should be `NOT NULL`. DB-wise I have this approach:
```
  `variables` varchar(8192) NOT NULL DEFAULT '{}',
```
This is generally enough to solve the issue. I'm not sure if changing groups from list to dict will not have any implications on the code.
